---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: demo-chat
  labels:
    service: demo-chat
    revision: {{CF_REVISION}}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: demo-chat
    spec:
      containers:
      - image: r.cfcr.io/{{CF_REPO_OWNER}}/{{CF_REPO_NAME}}:{{CF_SHORT_REVISION}}
        name: app
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          protocol: TCP
